---

version: 2.1

executors:
  test:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    working_directory: ~/repo

jobs:
  docker_compose_build:
    executor: test
    steps:
      - checkout
      - run:
          name: run stack
          command: >-
            docker-compose up
            --build
            --quiet-pull
            --force-recreate
            -d
      - run:
          name: manage database in rails
          command: >-
            docker-compose exec web rake db:create &&
            docker-compose exec web rake db:migrate &&
            docker-compose exec web rake db:seed
      - persist_to_workspace:
          root: .
          paths:
            - "."
      - run:
          name: execute tests
          command: >-
            docker-compose exec web
            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              -P "spec/**/*_spec.rb"
workflows:
  version: 2
  build_test:
    jobs:
      - docker_compose_build

...
